(define (problem p1) (:domain redflix_ext2)
(:objects 
Spiderman_No_Way_Home Thor_El_Mundo_Oscuro Thor_Ragnarok Los_Vengadores_La_Era_de_Ultron Los_Vengadores SpiderMan_Into_the_Spiderverse Thor Eternals Guardianes_de_la_Galaxia Capitan_America_El_Soldado_de_Invierno - contenido
Dia1 Dia2 Dia3 Dia4 Dia5 Dia6 Dia7 Dia8 Dia9 Dia10 Dia11 Dia12 Dia13 Dia14 Dia15 Dia16 Dia17 Dia18 Dia19 Dia20 - dia
)
(:init
  (diaAnterior Dia1 Dia2)
  (diaAnterior Dia2 Dia3)
  (diaAnterior Dia3 Dia4)
  (diaAnterior Dia4 Dia5)
  (diaAnterior Dia5 Dia6)
  (diaAnterior Dia6 Dia7)
  (diaAnterior Dia7 Dia8)
  (diaAnterior Dia8 Dia9)
  (diaAnterior Dia9 Dia10)
  (diaAnterior Dia10 Dia11)
  (diaAnterior Dia11 Dia12)
  (diaAnterior Dia12 Dia13)
  (diaAnterior Dia13 Dia14)
  (diaAnterior Dia14 Dia15)
  (diaAnterior Dia15 Dia16)
  (diaAnterior Dia16 Dia17)
  (diaAnterior Dia17 Dia18)
  (diaAnterior Dia18 Dia19)
  (diaAnterior Dia19 Dia20)

  (contenidoDisponible Spiderman_No_Way_Home)
  (contenidoDisponible Thor_El_Mundo_Oscuro)
  (contenidoDisponible Thor_Ragnarok)
  (contenidoDisponible Los_Vengadores_La_Era_de_Ultron)
  (contenidoDisponible Los_Vengadores)
  (contenidoDisponible SpiderMan_Into_the_Spiderverse)
  (contenidoDisponible Thor)
  (contenidoDisponible Eternals)
  (contenidoDisponible Guardianes_de_la_Galaxia)
  (contenidoDisponible Capitan_America_El_Soldado_de_Invierno)

  (predecesor Thor Thor_El_Mundo_Oscuro)
  (predecesor Thor_El_Mundo_Oscuro Thor_Ragnarok)
  (predecesor Los_Vengadores Los_Vengadores_La_Era_de_Ultron)
  (predecesor Capitan_America_El_Soldado_de_Invierno Thor)
  (predecesor Thor Thor_El_Mundo_Oscuro)
  (predecesor Thor_El_Mundo_Oscuro Thor_Ragnarok)
  (predecesor Thor_Ragnarok Guardianes_de_la_Galaxia)
  (predecesor Guardianes_de_la_Galaxia Los_Vengadores)
  (predecesor Los_Vengadores Los_Vengadores_La_Era_de_Ultron)
  (predecesor Los_Vengadores_La_Era_de_Ultron Spiderman_No_Way_Home)
  (predecesor Spiderman_No_Way_Home Eternals)
  (predecesor Eternals SpiderMan_Into_the_Spiderverse)

  (paralelo Thor_El_Mundo_Oscuro Guardianes_de_la_Galaxia)

)
(:goal (and (contenidoVisto Los_Vengadores) (contenidoVisto Guardianes_de_la_Galaxia) ))
)
