(define (problem p1) (:domain redflix_ext4)
(:objects 
Guardianes_de_la_Galaxia Los_Vengadores_Endgame Shang_Chi_y_la_Legenda_de_los_Diez_Anillos Thor_Ragnarok Capitan_America_Civil_War Doctor_Strange Doctor_Strange_en_el_Multiverso_de_la_Locura Guardianes_de_la_Galaxia_Vol_2 Iron_Man_2 Ant-Man - contenido
Dia1 Dia2 Dia3 Dia4 Dia5 Dia6 Dia7 Dia8 Dia9 Dia10 Dia11 Dia12 Dia13 Dia14 Dia15 - dia
)
(:init
  (diaAnterior Dia1 Dia2)
  (diaAnterior Dia2 Dia3)
  (diaAnterior Dia3 Dia4)
  (diaAnterior Dia4 Dia5)
  (diaAnterior Dia5 Dia6)
  (diaAnterior Dia6 Dia7)
  (diaAnterior Dia7 Dia8)
  (diaAnterior Dia8 Dia9)
  (diaAnterior Dia9 Dia10)
  (diaAnterior Dia10 Dia11)
  (diaAnterior Dia11 Dia12)
  (diaAnterior Dia12 Dia13)
  (diaAnterior Dia13 Dia14)
  (diaAnterior Dia14 Dia15)
)
  (= (duracion Guardianes_de_la_Galaxia) 70)
  (= (duracion Los_Vengadores_Endgame) 83)
  (= (duracion Shang_Chi_y_la_Legenda_de_los_Diez_Anillos) 74)
  (= (duracion Thor_Ragnarok) 106)
  (= (duracion Capitan_America_Civil_War) 116)
  (= (duracion Doctor_Strange) 77)
  (= (duracion Doctor_Strange_en_el_Multiverso_de_la_Locura) 104)
  (= (duracion Guardianes_de_la_Galaxia_Vol_2) 118)
  (= (duracion Iron_Man_2) 101)
  (= (duracion Ant-Man) 105)
)
  (contenidoDisponible Guardianes_de_la_Galaxia)
  (contenidoDisponible Los_Vengadores_Endgame)
  (contenidoDisponible Shang_Chi_y_la_Legenda_de_los_Diez_Anillos)
  (contenidoDisponible Thor_Ragnarok)
  (contenidoDisponible Capitan_America_Civil_War)
  (contenidoDisponible Doctor_Strange)
  (contenidoDisponible Doctor_Strange_en_el_Multiverso_de_la_Locura)
  (contenidoDisponible Guardianes_de_la_Galaxia_Vol_2)
  (contenidoDisponible Iron_Man_2)
  (contenidoDisponible Ant-Man)
)
  (predecesor Guardianes_de_la_Galaxia Guardianes_de_la_Galaxia_Vol_2)
  (predecesor Capitan_America_Civil_War Iron_Man_2)
  (predecesor Iron_Man_2 Thor_Ragnarok)
  (predecesor Thor_Ragnarok Guardianes_de_la_Galaxia)
  (predecesor Guardianes_de_la_Galaxia Guardianes_de_la_Galaxia_Vol_2)
  (predecesor Guardianes_de_la_Galaxia_Vol_2 Los_Vengadores_Endgame)
  (predecesor Los_Vengadores_Endgame Doctor_Strange)
  (predecesor Doctor_Strange Ant-Man)
  (predecesor Ant-Man Shang_Chi_y_la_Legenda_de_los_Diez_Anillos)
  (predecesor Shang_Chi_y_la_Legenda_de_los_Diez_Anillos Doctor_Strange_en_el_Multiverso_de_la_Locura)
)
  (paralelo Guardianes_de_la_Galaxia Thor_Ragnarok)
  (paralelo Los_Vengadores_Endgame Doctor_Strange_en_el_Multiverso_de_la_Locura)
  (paralelo Thor_Ragnarok Iron_Man_2)
  (paralelo Doctor_Strange Iron_Man_2)
)
(:goal (and (contenidoVisto Los_Vengadores_Endgame) (contenidoVisto Guardianes_de_la_Galaxia) (contenidoVisto Doctor_Strange_en_el_Multiverso_de_la_Locura) ))
)
