(define (problem p1) (:domain redflix)
(:objects 
Black_Panther_Wakanda_Forever Shang_Chi_y_la_Legenda_de_los_Diez_Anillos Spiderman_Far_From_Home SpiderMan_Into_the_Spiderverse Eternals Iron_Man_2 Thor_Ragnarok Thor_Love_and_Thunder Spiderman_Homecoming Iron_Man - contenido
Dia1 Dia2 Dia3 Dia4 Dia5 Dia6 Dia7 Dia8 Dia9 Dia10 Dia11 Dia12 Dia13 Dia14 Dia15 Dia16 Dia17 Dia18 Dia19 Dia20 - dia
)
(:init
  (diaAnterior Dia1 Dia2)
  (diaAnterior Dia2 Dia3)
  (diaAnterior Dia3 Dia4)
  (diaAnterior Dia4 Dia5)
  (diaAnterior Dia5 Dia6)
  (diaAnterior Dia6 Dia7)
  (diaAnterior Dia7 Dia8)
  (diaAnterior Dia8 Dia9)
  (diaAnterior Dia9 Dia10)
  (diaAnterior Dia10 Dia11)
  (diaAnterior Dia11 Dia12)
  (diaAnterior Dia12 Dia13)
  (diaAnterior Dia13 Dia14)
  (diaAnterior Dia14 Dia15)
  (diaAnterior Dia15 Dia16)
  (diaAnterior Dia16 Dia17)
  (diaAnterior Dia17 Dia18)
  (diaAnterior Dia18 Dia19)
  (diaAnterior Dia19 Dia20)

  (contenidoDisponible Black_Panther_Wakanda_Forever)
  (contenidoDisponible Shang_Chi_y_la_Legenda_de_los_Diez_Anillos)
  (contenidoDisponible Spiderman_Far_From_Home)
  (contenidoDisponible SpiderMan_Into_the_Spiderverse)
  (contenidoDisponible Eternals)
  (contenidoDisponible Iron_Man_2)
  (contenidoDisponible Thor_Ragnarok)
  (contenidoDisponible Thor_Love_and_Thunder)
  (contenidoDisponible Spiderman_Homecoming)
  (contenidoDisponible Iron_Man)

  (predecesor Iron_Man Iron_Man_2)
  (predecesor Spiderman_Homecoming Spiderman_Far_From_Home)
  (predecesor Iron_Man Iron_Man_2)
  (predecesor Iron_Man_2 Thor_Ragnarok)
  (predecesor Thor_Ragnarok Spiderman_Homecoming)
  (predecesor Spiderman_Homecoming Spiderman_Far_From_Home)
  (predecesor Spiderman_Far_From_Home Shang_Chi_y_la_Legenda_de_los_Diez_Anillos)
  (predecesor Shang_Chi_y_la_Legenda_de_los_Diez_Anillos Eternals)
  (predecesor Eternals SpiderMan_Into_the_Spiderverse)
  (predecesor SpiderMan_Into_the_Spiderverse Thor_Love_and_Thunder)
  (predecesor Thor_Love_and_Thunder Black_Panther_Wakanda_Forever)

)
(:goal (and (contenidoVisto Iron_Man_2) (enDia Iron_Man_2 Dia19)))
)
