(define (problem p1) (:domain redflix_ext2)
(:objects 
Star_Trek_La_Película Capitán_América_El_Primer_Vengador Doctor_Strange Star_Trek_La_Serie_Original_T1_C2 Star_Trek_La_Serie_Original_T1_C1 Torchwood_T1_C1 Torchwood_T1_C2 Shazam Capitán_América_El_Soldado_de_Invierno Stargate_SG-1_T1_C2 - contenido
Dia1 Dia2 Dia3 Dia4 Dia5 Dia6 Dia7 Dia8 Dia9 Dia10 Dia11 Dia12 Dia13 Dia14 Dia15 Dia16 Dia17 Dia18 Dia19 Dia20 - dia
)
(:init
  (diaAnterior Dia1 Dia2)
  (diaAnterior Dia2 Dia3)
  (diaAnterior Dia3 Dia4)
  (diaAnterior Dia4 Dia5)
  (diaAnterior Dia5 Dia6)
  (diaAnterior Dia6 Dia7)
  (diaAnterior Dia7 Dia8)
  (diaAnterior Dia8 Dia9)
  (diaAnterior Dia9 Dia10)
  (diaAnterior Dia10 Dia11)
  (diaAnterior Dia11 Dia12)
  (diaAnterior Dia12 Dia13)
  (diaAnterior Dia13 Dia14)
  (diaAnterior Dia14 Dia15)
  (diaAnterior Dia15 Dia16)
  (diaAnterior Dia16 Dia17)
  (diaAnterior Dia17 Dia18)
  (diaAnterior Dia18 Dia19)
  (diaAnterior Dia19 Dia20)

  (contenidoDisponible Star_Trek_La_Película)
  (contenidoDisponible Capitán_América_El_Primer_Vengador)
  (contenidoDisponible Doctor_Strange)
  (contenidoDisponible Star_Trek_La_Serie_Original_T1_C2)
  (contenidoDisponible Star_Trek_La_Serie_Original_T1_C1)
  (contenidoDisponible Torchwood_T1_C1)
  (contenidoDisponible Torchwood_T1_C2)
  (contenidoDisponible Shazam)
  (contenidoDisponible Capitán_América_El_Soldado_de_Invierno)
  (contenidoDisponible Stargate_SG-1_T1_C2)

  (predecesor Capitán_América_El_Primer_Vengador Doctor_Strange)
  (predecesor Star_Trek_La_Serie_Original_T1_C1 Star_Trek_La_Serie_Original_T1_C2)
  (predecesor Torchwood_T1_C2 Torchwood_T1_C1)
  (predecesor Star_Trek_La_Serie_Original_T1_C2 Star_Trek_La_Serie_Original_T1_C2)
  (predecesor Star_Trek_La_Serie_Original_T1_C1 Star_Trek_La_Serie_Original_T1_C1)
  (predecesor Torchwood_T1_C1 Torchwood_T1_C1)
  (predecesor Torchwood_T1_C2 Torchwood_T1_C2)
  (predecesor Stargate_SG-1_T1_C2 Stargate_SG-1_T1_C2)
  (paralelo Star_Trek_La_Serie_Original_T1_C2 Star_Trek_La_Serie_Original_T1_C1)
  (paralelo Star_Trek_La_Serie_Original_T1_C1 Star_Trek_La_Serie_Original_T1_C2)
  (paralelo Torchwood_T1_C1 Torchwood_T1_C2)
  (paralelo Torchwood_T1_C2 Torchwood_T1_C1)

)
(:goal (and (contenidoVisto Capitán_América_El_Soldado_de_Invierno) (enDia Capitán_América_El_Soldado_de_Invierno Dia6)))
)
