(define (problem p2) (:domain redflix_optimized)
    (:requirements :fluents)
(:objects 
Capitan_America_El_Primer_Vengador Capitana_Marvel Iron_Man Iron_Man_2 Thor Los_Vengadores Iron_Man_3 Thor_El_Mundo_Oscuro Capitan_America_El_Soldado_de_Invierno Guardianes_de_la_Galaxia Guardianes_de_la_Galaxia_Vol_2 Los_Vengadores_La_Era_de_Ultron Ant-Man Capitan_America_Civil_War Spiderman_Homecoming Doctor_Strange Black_Panther Thor_Ragnarok Ant-Man_and_the_Wasp Los_Vengadores_Infinity_War Los_Vengadores_Endgame - contenido
Dia1 Dia2 Dia3 Dia4 - dia

)

(:init
    (diaAnterior Dia1 Dia2)
    (diaAnterior Dia2 Dia3)
    (diaAnterior Dia3 Dia4)

    (= (minutosDia Dia1) 0)
    (= (minutosDia Dia2) 0)
    (= (minutosDia Dia3) 0)
    (= (minutosDia Dia4) 0)

    (contenidoDisponible Capitan_America_El_Primer_Vengador)
    (contenidoDisponible Capitana_Marvel)
    (contenidoDisponible Iron_Man)
    (contenidoDisponible Iron_Man_2)
    (contenidoDisponible Thor)
    (contenidoDisponible Los_Vengadores)
    (contenidoDisponible Iron_Man_3)
    (contenidoDisponible Thor_El_Mundo_Oscuro)
    (contenidoDisponible Capitan_America_El_Soldado_de_Invierno)
    (contenidoDisponible Guardianes_de_la_Galaxia)
    (contenidoDisponible Guardianes_de_la_Galaxia_Vol_2)
    (contenidoDisponible Los_Vengadores_La_Era_de_Ultron)
    (contenidoDisponible Ant-Man)
    (contenidoDisponible Capitan_America_Civil_War)
    (contenidoDisponible Spiderman_Homecoming)
    (contenidoDisponible Doctor_Strange)
    (contenidoDisponible Black_Panther)
    (contenidoDisponible Thor_Ragnarok)
    (contenidoDisponible Ant-Man_and_the_Wasp)
    (contenidoDisponible Los_Vengadores_Infinity_War)
    (contenidoDisponible Los_Vengadores_Endgame)


    (=(duracion Capitan_America_El_Primer_Vengador)60)
    (=(duracion Capitana_Marvel)60)
    (=(duracion Iron_Man)60)
    (=(duracion Iron_Man_2)60)
    (=(duracion Thor)60)
    (=(duracion Los_Vengadores)60)
    (=(duracion Iron_Man_3)60)
    (=(duracion Thor_El_Mundo_Oscuro)60)
    (=(duracion Capitan_America_El_Soldado_de_Invierno)60)
    (=(duracion Guardianes_de_la_Galaxia)60)
    (=(duracion Guardianes_de_la_Galaxia_Vol_2)60)
    (=(duracion Los_Vengadores_La_Era_de_Ultron)60)
    (=(duracion Ant-Man)60)
    (=(duracion Capitan_America_Civil_War)60)
    (=(duracion Spiderman_Homecoming)60)
    (=(duracion Doctor_Strange)60)
    (=(duracion Black_Panther)60)
    (=(duracion Thor_Ragnarok)60)
    (=(duracion Ant-Man_and_the_Wasp)60)
    (=(duracion Los_Vengadores_Infinity_War)60)
    (=(duracion Los_Vengadores_Endgame)60)

    (paralelo Capitan_America_El_Primer_Vengador Los_Vengadores)
    (paralelo Capitana_Marvel Los_Vengadores)
    (paralelo Iron_Man Los_Vengadores)
    (paralelo Iron_Man_2 Los_Vengadores)
    (paralelo Thor Los_Vengadores)
    (paralelo Iron_Man_3 Los_Vengadores_La_Era_de_Ultron)
    (paralelo Thor_El_Mundo_Oscuro Los_Vengadores_La_Era_de_Ultron)
    (paralelo Capitan_America_El_Soldado_de_Invierno Los_Vengadores_La_Era_de_Ultron)
    (paralelo Guardianes_de_la_Galaxia Los_Vengadores_La_Era_de_Ultron)
    (paralelo Guardianes_de_la_Galaxia_Vol_2 Los_Vengadores_La_Era_de_Ultron)
    (paralelo Ant-Man Los_Vengadores_La_Era_de_Ultron)
    (paralelo Capitan_America_Civil_War Los_Vengadores_La_Era_de_Ultron)
    (paralelo Spiderman_Homecoming Los_Vengadores_La_Era_de_Ultron)
    (paralelo Doctor_Strange Los_Vengadores_La_Era_de_Ultron)
    (paralelo Black_Panther Los_Vengadores_La_Era_de_Ultron)
    (paralelo Thor_Ragnarok Los_Vengadores_La_Era_de_Ultron)
    (paralelo Ant-Man_and_the_Wasp Los_Vengadores_La_Era_de_Ultron)

    (predecesor Iron_Man Iron_Man_2)
    (predecesor Iron_Man_2 Iron_Man_3)
    (predecesor Thor Thor_El_Mundo_Oscuro)
    (predecesor Thor_El_Mundo_Oscuro Thor_Ragnarok)
    (predecesor Capitan_America_El_Primer_Vengador Capitan_America_El_Soldado_de_Invierno)
    (predecesor Capitan_America_El_Soldado_de_Invierno Capitan_America_Civil_War)
    (predecesor Ant-Man Ant-Man_and_the_Wasp)
    (predecesor Guardianes_de_la_Galaxia Guardianes_de_la_Galaxia_Vol_2)
    (predecesor Los_Vengadores Los_Vengadores_La_Era_de_Ultron)
    (predecesor Los_Vengadores_La_Era_de_Ultron Los_Vengadores_Infinity_War)
    (predecesor Los_Vengadores_Infinity_War Los_Vengadores_Endgame)
    

)

(:goal (contenidoVisto Iron_Man_3)

)
)
