(define (problem p1) (:domain redflix)
(:objects 
Capitan_America_El_Primer_Vengador Capitana_Marvel Iron_Man Iron_Man_2 Thor Los_Vengadores Iron_Man_3 Thor_El_Mundo_Oscuro Capitan_America_El_Soldado_de_Invierno Guardianes_de_la_Galaxia Guardianes_de_la_Galaxia_Vol_2 Los_Vengadores_La_Era_de_Ultron Ant-Man Capitan_America_Civil_War Spiderman_Homecoming Doctor_Strange Black_Panther Thor_Ragnarok Ant-Man_and_the_Wasp Los_Vengadores_Infinity_War Los_Vengadores_Endgame - contenido
)

(:init
    (contenidoDisponible Capitan_America_El_Primer_Vengador)
    (contenidoDisponible Capitana_Marvel)
    (contenidoDisponible Iron_Man)
    (contenidoDisponible Iron_Man_2)
    (contenidoDisponible Thor)
    (contenidoDisponible Los_Vengadores)
    (contenidoDisponible Iron_Man_3)
    (contenidoDisponible Thor_El_Mundo_Oscuro)
    (contenidoDisponible Capitan_America_El_Soldado_de_Invierno)
    (contenidoDisponible Guardianes_de_la_Galaxia)
    (contenidoDisponible Guardianes_de_la_Galaxia_Vol_2)
    (contenidoDisponible Los_Vengadores_La_Era_de_Ultron)
    (contenidoDisponible Ant-Man)
    (contenidoDisponible Capitan_America_Civil_War)
    (contenidoDisponible Spiderman_Homecoming)
    (contenidoDisponible Doctor_Strange)
    (contenidoDisponible Black_Panther)
    (contenidoDisponible Thor_Ragnarok)
    (contenidoDisponible Ant-Man_and_the_Wasp)
    (contenidoDisponible Los_Vengadores_Infinity_War)
    (contenidoDisponible Los_Vengadores_Endgame)

    (predecesor Iron_Man Iron_Man_2)
    (predecesor Iron_Man_2 Iron_Man_3)
    (predecesor Thor Thor_El_Mundo_Oscuro)
    (predecesor Thor_El_Mundo_Oscuro Thor_Ragnarok)
    (predecesor Capitan_America_El_Primer_Vengador Capitan_America_El_Soldado_de_Invierno)
    (predecesor Capitan_America_El_Soldado_de_Invierno Capitan_America_Civil_War)
    (predecesor Ant-Man Ant-Man_and_the_Wasp)
    (predecesor Guardianes_de_la_Galaxia Guardianes_de_la_Galaxia_Vol_2)
    (predecesor Los_Vengadores Los_Vengadores_La_Era_de_Ultron)
    (predecesor Los_Vengadores_La_Era_de_Ultron Los_Vengadores_Infinity_War)
    (predecesor Los_Vengadores_Infinity_War Los_Vengadores_Endgame)

    (predecesor Thor Los_Vengadores)
    (predecesor Iron_Man_2 Los_Vengadores)
    (predecesor Capitan_America_El_Primer_Vengador Los_Vengadores)
    (predecesor Capitana_Marvel Los_Vengadores)
    (predecesor Guardianes_de_la_Galaxia_Vol_2 Los_Vengadores_La_Era_de_Ultron)
    (predecesor Capitan_America_El_Soldado_de_Invierno Los_Vengadores_La_Era_de_Ultron)
    (predecesor Thor_El_Mundo_Oscuro Los_Vengadores_La_Era_de_Ultron)
    (predecesor Iron_Man_3 Los_Vengadores_La_Era_de_Ultron)
    (predecesor Ant-Man_and_the_Wasp Los_Vengadores_Infinity_War)
    (predecesor Black_Panther Los_Vengadores_Infinity_War)
    (predecesor Doctor_Strange Los_Vengadores_Infinity_War)
    (predecesor Spiderman_Homecoming Los_Vengadores_Infinity_War)
    (predecesor Capitan_America_Civil_War Los_Vengadores_Infinity_War)
    (predecesor Thor_Ragnarok Los_Vengadores_Infinity_War)
    (predecesor Los_Vengadores_Infinity_War Los_Vengadores_Endgame)
)

(:goal (contenidoPorVer Los_Vengadores_Endgame))

)
